version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: medicine_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - prescription-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    depends_on:
      - mongodb
    restart: always
    networks:
      - prescription-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - prescription-network

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=your_secure_password
    ports:
      - "6379:6379"
    networks:
      - prescription-network

  gateway:
    build:
      context: .
      dockerfile: src/Services/APIGateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - authentication
      - medicine
      - prescription
    networks:
      - prescription-network

  authentication:
    build:
      context: .
      dockerfile: src/Services/AuthService/Dockerfile
    container_name: authentication
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    ports:
      - "5010:80"
      - "5011:443"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - prescription-network

  medicine:
    build:
      context: .
      dockerfile: src/Services/MedicineService/Dockerfile
    container_name: medicine
    ports:
      - "5020:80"
      - "5021:443"
    depends_on:
      - mongodb
    networks:
      - prescription-network

  prescription:
    build:
      context: .
      dockerfile: src/Services/PrescriptionService/Dockerfile
    container_name: prescription
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PrescriptionDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    ports:
      - "5030:80"
      - "5031:443"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - prescription-network

networks:
  prescription-network:
    driver: bridge

volumes:
  mongodb_data:
  sqlserver_data:
